PARAMETER_MAPPING = {
    "factory_parameter_d": {
        "name": "D",
        "bar": [1, 8, 11],
        "frequency": [],
        "amper": [],
        "temperature": [0, 2, 6, 7, 9, 10],
        "duration_min": [3, 4],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [5],
        "bar_parameter": "-bar"
    },
    "factory_parameter_e": {
        "name": "E",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [1, 6, 10],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [8]
    },
    "factory_parameter_fh0": {
        "name": "F",
        "bar": [2, 4, 6, 8, 10, 12],
        "frequency": [],
        "amper": [],
        "temperature": [1, 3, 5, 7, 9, 11],
        "duration_min": [],
        "duration_h": [20, 21],
        "percentage": [14, 16, 18, 22, 26],
        "rotation": [15, 17, 19, 23, 27],
        "skip": [8, 9],
        "bar_parameter": "-bar",
        "rotation_parameter": "-r"
    },
    "factory_parameter_h": {
        "name": "H",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [2],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [4, 5]
    },
    "factory_parameter_p": {
        "name": "P",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [1, 2, 3],
        "duration_h": [5, 6, 7, 8],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_r": {
        "name": "R",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [6, 7]
    },
    "factory_parameter_o": {
        "name": "O",
        "bar": [],
        "frequency": [6],
        "amper": [7],
        "temperature": [8],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_s": {
        "name": "S",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_t": {
        "name": "T",
        "bar": [9],
        "frequency": [8],
        "amper": [6],
        "volt": [13, 18],
        "temperature": [0, 1, 2, 3, 4, 5, 10, 12, 14, 21],
        "duration_min": [],
        "duration_h": [],
        "percentage": [7],
        "rotation": [11, 15, 16, 17],
        "skip": []
    },
}
