#!/bin/bash
path=`pwd`
sysctlpath="/lib/systemd/system/"

if [ -z $1 ]; then
	echo use with setup_systemctl install/uninstall
	exit 1
fi

if [ $1 = "install" ]; then
cat > $sysctlpath/aquatemp_control.service << EOF
[Unit]
Description=Heatpump_control
After=network-online.target

[Service]
Type=simple
ExecStart=${path}/control.sh

[Install]
WantedBy=multi-user.target
EOF
cat > $sysctlpath/aquatemp_status.service << EOF
[Unit]
Description=Heatpump_control
After=network-online.target

[Service]
Type=simple
ExecStart=${path}/status.sh

[Install]
WantedBy=multi-user.target
EOF

systemctl enable aquatemp_control.service
systemctl enable aquatemp_status.service
systemctl start aquatemp_control.service
systemctl start aquatemp_status.service

elif [ $1 = "uninstall" ]; then
	systemctl stop aquatemp_control.service
	systemctl stop aquatemp_status.service
	systemctl disable aquatemp_control.service
	systemctl disable aquatemp_status.service
	rm -f $sysctlpath/aquatemp_control.service
	rm -f $sysctlpath/aquatemp_status.service
	

fi
