PARAMETER_MAPPING = {
    "factory_parameter_d": {
        "name": "D",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_e": {
        "name": "E",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_fh0": {
        "name": "F",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_h": {
        "name": "H",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_p": {
        "name": "P",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_r": {
        "name": "R",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_o": {
        "name": "O",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_s": {
        "name": "S",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_t": {
        "name": "T",
        "bar": [],
        "frequency": [],
        "amper": [],
        "volt": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
}
