PARAMETER_MAPPING = {
    "factory_parameter_d": {
        "name": "D",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0, 1, 6],
        "duration_min": [2, 3, 4],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_e": {
        "name": "E",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [1],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_g": {
        "name": "G",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0],
        "duration_min": [1],
        "duration_h": [2],
        "duration_d": [3],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_h": {
        "name": "H",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [5],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [2, 4, 5, 6, 8, 9,
                 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                 33, 34, 35, 36, 37, 38, 39,
                 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
                 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
                 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
                 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                 90, 91, 92, 93, 94, 95, 96, 97
                 ]
    },
    "factory_parameter_n": {
        "name": "N",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [2, 6, 7, 8, 9],
        "duration_min": [1],
        "duration_h": [5],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_r": {
        "name": "R",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0, 1, 3, 6, 7, 8, 9, 10, 11, 13, 14, 15],
        "duration_min": [4],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [2, 11, 13, 16]
    },
    "status_parameter_o": {
        "name": "O",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [7, 8],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "status_parameter_s": {
        "name": "S",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "status_parameter_t": {
        "name": "T",
        "bar": [],
        "frequency": [],
        "amper": [],
        "volt": [],
        "temperature": [0, 1, 2, 3, 4, 5, 6],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": [7, 8, 9]
    },
    "_factory_parameter": {
        "name": "/",
        "bar": [],
        "frequency": [],
        "amper": [],
        "volt": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
}
