PARAMETER_MAPPING = {
    "factory_parameter_d": {
        "name": "D",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0, 1],
        "duration_min": [2, 3, 4],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_e": {
        "name": "E",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [1],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_g": {
        "name": "G",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [0],
        "duration_min": [1],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_h": {
        "name": "H",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_n": {
        "name": "N",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [2, 3, 4, 5, 6, 7, 8, 9, 10],
        "duration_min": [0, 1],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "factory_parameter_r": {
        "name": "R",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "status_parameter_o": {
        "name": "O",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "status_parameter_s": {
        "name": "S",
        "bar": [],
        "frequency": [],
        "amper": [],
        "temperature": [],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
    "status_parameter_t": {
        "name": "T",
        "bar": [],
        "frequency": [],
        "amper": [],
        "volt": [],
        "temperature": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "duration_min": [],
        "duration_h": [],
        "percentage": [],
        "rotation": [],
        "skip": []
    },
}
