from homeassistant.components.climate.const import FAN_AUTO, FAN_LOW

from .endpoints import Endpoints

DOMAIN = "aqua_temp"
DEFAULT_NAME = "Aqua Temp"
SIGNAL_AQUA_TEMP_DEVICE_NEW = f"signal_{DOMAIN}_device_new"

HTTP_HEADER_X_TOKEN = "x-token"

SUPPORTED_PRODUCT_ID = [
    "1132174963097280512",
    "1186904563333062656",
    "1158905952238313472",
    "1245226668902080512",
    "1442284873216843776",
    "1548963836789501952",
]

DEVICE_REQUEST_PRODUCT_IDS = "product_ids"
DEVICE_REQUEST_PAGE_INDEX = "page_index"
DEVICE_REQUEST_PAGE_SIZE = "page_size"
DEVICE_REQUEST_TO_USER = "to_user"

DEVICE_CODE = "device_code"
DEVICE_PRODUCT_ID = "product_id"
PROTOCAL_CODES = "protocal_codes"

DEVICE_CONTROL_PARAM = "param"

DEVICE_CONTROL_PROTOCOL_CODE = "protocol_code"
DEVICE_CONTROL_VALUE = "value"

DEVICE_REQUEST_PARAMETERS = {
    DEVICE_REQUEST_PRODUCT_IDS: SUPPORTED_PRODUCT_ID,
    DEVICE_REQUEST_PAGE_INDEX: 1,
    DEVICE_REQUEST_PAGE_SIZE: 999,
}

DEVICE_LISTS = {
    Endpoints.LIST_REGISTERED_DEVICES: [
        DEVICE_REQUEST_PRODUCT_IDS,
        DEVICE_REQUEST_PAGE_INDEX,
        DEVICE_REQUEST_PAGE_SIZE,
    ],
    Endpoints.LIST_SHARED_TOBE_DEVICES: [
        DEVICE_REQUEST_PRODUCT_IDS,
        DEVICE_REQUEST_TO_USER,
    ],
    Endpoints.LIST_SHARED_APPECT_DEVICES: [
        DEVICE_REQUEST_PRODUCT_IDS,
        DEVICE_REQUEST_TO_USER,
        DEVICE_REQUEST_PAGE_INDEX,
        DEVICE_REQUEST_PAGE_SIZE,
    ],
}

MANUAL_MUTE_AUTO = "0"
MANUAL_MUTE_LOW = "1"

FAN_MODE_MAPPING = {FAN_AUTO: MANUAL_MUTE_AUTO, FAN_LOW: MANUAL_MUTE_LOW}

POWER_MODE_OFF = "0"
POWER_MODE_ON = "1"

HEADERS = {"Content-Type": "application/json; charset=utf-8"}

DATA_ITEM_DEVICES = "device"
DATA_ITEM_LOGIN_DETAILS = "login-details"
DATA_ITEM_CONFIG = "configuration"
