class Endpoints:
    Login = "app/user/login"
    UserInfo = "app/user/getUserInfo"
    ListRegisteredDevices = "app/device/deviceList"
    ListSharedAppectDevices = "app/device/getMyAppectDeviceShareDataList"
    ListSharedTobeDevices = "app/device/getMyTobeAppectDeviceShareDataList"
    DeviceStatus = "app/device/getDeviceStatus"
    DeviceControl = "app/device/control"
    DeviceFault = "app/device/getFaultDataByDeviceCode"
    DeviceData = "app/device/getDataByCode"
    DevicePassthroughInstruction = "device/sendDevicePassthroughInstruction"
